import { describe, expect, it, vi } from "vitest";
import { createTwilioStatusWebhookHandler, createTwilioWhatsappWebhookHandler, statusCallbackUrl } from "./webhookHandler.js";

function response(){return{code:0,typeValue:"",body:"",status(code:number){this.code=code;return this},type(value:string){this.typeValue=value;return this},send(value:string){this.body=value;return this},sendStatus(code:number){this.code=code;return this}}}
function config(){return{nodeEnv:"test",webhookPort:3000,operatorPort:3100,operatorHost:"127.0.0.1",logLevel:"error",webhookEventLog:{path:":memory:"},operator:{databasePath:":memory:",mediaPath:".runtime/test-media",settingsPath:".runtime/test-settings.json",demoMode:true},inboundBuffer:{idleMs:0},twilio:{},inventory:{provider:"mock_grocery"},agent:{mode:"deterministic",timeoutMs:1000},shopify:{}} as never}

describe("Twilio webhook handlers",()=>{
  it("persists before acknowledging and suppresses automation in human mode",async()=>{const ingestInbound=vi.fn(()=>({created:true,createdConversation:false,conversationId:"c1",contactId:"ct1",messageId:"m1",mode:"human",mediaIds:[]})),sendMessage=vi.fn(),send=vi.fn();const runtime={repository:{ingestInbound,listPendingMedia:()=>[]},events:{publish:vi.fn()},sendMessage,settings:{current:{handoffMessage:"handoff"}}};const res=response();res.send=send as never;await createTwilioWhatsappWebhookHandler(config(),runtime as never)({body:{MessageSid:"SM1",From:"whatsapp:+573001234567",Body:"Hola"}} as never,res as never);expect(ingestInbound).toHaveBeenCalledOnce();expect(send).toHaveBeenCalledWith("<Response></Response>");expect(ingestInbound.mock.invocationCallOrder[0]).toBeLessThan(send.mock.invocationCallOrder[0]);await new Promise(r=>setTimeout(r,5));expect(sendMessage).not.toHaveBeenCalled()});
  it("records outbound delivery and read status callbacks",()=>{const updateMessageStatus=vi.fn(()=>true),publish=vi.fn(),res=response();createTwilioStatusWebhookHandler({repository:{updateMessageStatus},events:{publish}} as never)({body:{MessageSid:"SM2",MessageStatus:"read"}} as never,res as never);expect(updateMessageStatus).toHaveBeenCalledWith("SM2","read",undefined,undefined);expect(publish).toHaveBeenCalledWith({type:"message.status",data:{providerSid:"SM2",status:"read"}});expect(res.code).toBe(204)});
  it("builds the status callback on the approved public origin",()=>{expect(statusCallbackUrl("https://example.com/webhooks/twilio/whatsapp")).toBe("https://example.com/webhooks/twilio/status")});
});
